<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Rc car web Portfolio</title>

  <!-- OpenGraph and Twitter meta tags -->
  <meta property="og:type" content="website">
  <meta property="og:site_name" content="4조 RC카 웹사이트">
  <meta property="og:title" content="4조 웹사이트">
  <meta property="og:description" content="4조 RC카 웹사이트">
  <meta property="og:image" content="./images/profile.jpeg">
  <meta property="og:url" content="">

  <meta name="twitter:card" content="summary">
  <meta name="twitter:site" content="4조 RC카 웹사이트">
  <meta name="twitter:title" content="4조 RC카 웹사이트">
  <meta name="twitter:description" content="4조 RC카 웹사이트">
  <meta name="twitter:image" content="./images/profile.jpeg">
  <meta name="twitter:url" content="">

  <!-- Favicon -->
  <link rel="icon" href="./favicon.png">

  <!-- CSS Reset -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/reset-css@5.0.1/reset.min.css">

  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Black+Han+Sans&family=Noto+Sans+KR&display=swap" rel="stylesheet">

  <!-- Material Icons -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

  <!-- Main CSS -->
  <link rel="stylesheet" href="./css/main.css">

</head>
<body>
  <!-- HEADER -->
  <header id="Header">
    <div class="inner">
      <a class='maintitle' href='/'>4조 RC카 웹사이트 페이지</a>
      <div class="sub-menu">
        <ul class="menu">
          <li id="SkillInventory">
            <a href="javascript:void(0)" onclick="scrollToSection('skillinventory_section')">SkillInventory</a>
          </li>
          <li id="Archive">
            <a href="javascript:void(0)" onclick="scrollToSection('archive_section')">Archive</a>
          </li>
          <li id="Projects">
            <a href="javascript:void(0)" onclick="scrollToSection('projects_section')">Projects</a>
          </li>
          <li id="History">
            <a href="javascript:void(0)" onclick="scrollToSection('history_section')">Member</a>
          </li>
        </ul>
      </div>
    </div>
  </header>

  <!-- SUMMARY SECTION -->
  <section class="summary">
    <div class="inner">
      <div class="summary_Header">- 4조 RC카 웹사이트 -<br></div>
      <div class="summary_description">
        <p>안녕하세요. 4조 RC카 웹사이트 페이지 입니다.</p>
        <p>다양한 기능들과 우리조의 성장과정을 담아보았습니다.</p>
        <p>홈페이지에 확인하실수있습니다</p>
      </div>
      <button class="btn" id="see_more" onclick="scrollToSection('skillinventory_section')">더 알아보기 ↓</button>
      <br>
    </div>
  </section>

  <!-- SKILLINVENTORY SECTION -->
  <section class="skillinventory" id="skillinventory_section">
    <div class="inner">
      <div class="skillinventory_title">Skill Inventory</div>
      <div class="skillinventory_container">
        <div class="skillinventory_box">
          <div class="skillinventory_box_title">Front-End</div>
          <div class="skillinventory_box_des">
            <img src="https://cdn-icons-png.flaticon.com/512/5968/5968267.png" height="140">
            <img src="https://cdn-icons-png.flaticon.com/512/5968/5968242.png" height="140">
            <img src="https://cdn-icons-png.flaticon.com/512/5968/5968292.png" height="130">
          </div>
        </div>
        <div class="skillinventory_box">
          <div class="skillinventory_box_title">Back-End</div>
          <div class="skillinventory_box_des">
            <img src="https://cdn-icons-png.flaticon.com/512/226/226777.png" height="130">
            <img src="https://tomcat.apache.org/res/images/tomcat.png" height="100">
          </div>
        </div>
        <div class="skillinventory_box">
          <div class="skillinventory_box_title">Communication</div>
          <div class="skillinventory_box_des">
            <img src="https://cdn-icons-png.flaticon.com/512/5968/5968705.png" height="140">
            <img src="https://cdn-icons-png.flaticon.com/512/2111/2111615.png" height="80">
          </div>
        </div>
        <div class="skillinventory_box">
          <div class="skillinventory_box_title">Deployment</div>
          <div class="skillinventory_box_des">
            <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Netlify_logo.svg/1280px-Netlify_logo.svg.png" height="70">
          </div>
        </div>
        <div class="skillinventory_box">
          <div class="skillinventory_box_title">Storage</div>
          <div class="skillinventory_box_des">
            <img src="https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png" height="80">
          </div>
        </div>
        <div class="skillinventory_box">
          <div class="skillinventory_box_title">Tool</div>
          <div class="skillinventory_box_des">
            <img src="https://code.visualstudio.com/assets/images/code-stable.png" height="100">
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- ARCHIVE SECTION -->
  <section class="archive" id="archive_section">
    <div class="inner">
      <div class="archive_title">Archive</div>
      <div class="archive_containor">
        <div class="archive_box">
          <div class="archive_box_title">
            <img src="https://cdn-icons-png.flaticon.com/512/25/25657.png" height="40">
            <span class="textmiddle">과정</span>
          </div>
          <div class="archive_box_des">
            <a href="">우리가 해온 작업</a>
            <br>
            과정입니다.
            <br>
            <br>
            <ul>
              <li>현재까지 해온 프로젝트들 주차보고서 올릴예정</li>
              <br>
              <li>작업과정 링크달예정</li>
              <br>
              <li>시연영상 링크달예정 gif로 보이게할예정</li>
            </ul>
          </div>
        </div>
        <div class="archive_box">
          <div class="archive_box_title">
            <img src="https://cdn-icons-png.flaticon.com/512/3959/3959542.png" height="40">
            <span class="textmiddle">Blog</span>
          </div>
          <div class="archive_box_des">
            <a href="https://jeonspace.tistory.com/1">성장과정 </a>
            <br>
            https://jeonspace.tistory.com/1
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- PROJECTS SECTION -->
  <section class="projects" id="projects_section">
    <div class="inner">
      <div class="project">
        <div class="project_title">Projects</div>
        <div class="project_containor">
          <div class="project_box">
            <div class="project_box_title">RC카 시연영상</div>
            <div class="project_box_subtitle">240101 ~ 241030</div>
            <div class="project_box_des">
              <div class="project_box_des_left">
                <img src="https://blog.kakaocdn.net/dn/AHHr1/btsIjzMq3tr/wfxEWjmC8fzdXx3KteWFq1/img.gif" alt="" width="70%" height="100%">
              </div>
              <div class="project_box_des_right">
                <p>RC카 시연영상입니다</p>
                <br>
                <p>
                  라즈베리파이 연동및 다양한 러닝을 시킨뒤,
                  자율주행 RC카를 구축해야됩니다만 gif로 만들지 br주석 추가해서 더 추가해보겠습니다

                 

                 "이 프로젝트는 라즈베리파이를 이용해 RC카를 자율주행하도록 만든 시연영상입니다.
                  라즈베리파이는 다양한 센서와 카메라 모듈을 통해 주행 경로를 인식하고, 이를 바탕으로 RC카를 자동으로 제어합니다.
                  이 과정에서 머신 러닝 알고리즘을 적용하여 장애물을 피하거나 지정된 경로를 따라갈 수 있도록 설계되었습니다.
                  프로젝트의 목적과 성과를 명확하게 전달할 수 있습니다.
                </p>
              </div>
            </div>
          </div>
          <div class="project_box">
            <div class="project_box_title">자율주행</div>
            <div class="project_box_subtitle">240701 ~ 241030</div>
            <div class="project_box_des">
              <div class="project_box_des_left">
                <img src="https://blog.kakaocdn.net/dn/AYUM9/btsIiTR5sjT/GbxJbKXTHz8iTHfeIXpm5K/img.gif" alt="" width="100%" height="100%">
              </div>
              <div class="project_box_des_right">
                <p>자율주행 알고리즘 입니다</p>
                <br>
                <p>
                  가장최적화된 경로를 돌아가 RC카가 자율주행을 하도록
                  구현하였습니다. 나중에 보여드릴게요  예시사진입니다
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- MEMBER SECTION -->
  <section class="history" id="history_section">
    <div class="inner">
      <div class="history_title">Member</div>
      <div class="history_containor">
        <div class="history_box">
          <div class="history_box_title">4조 RC카 멤버</div>
          <div class="history_box_des">
            <p>프로젝트기간 20240101~20241030</p>
            <br>
            <p>
              프로젝트 동안을 정리한 것입니다.
              추가로 업로드하겠습니다 
              <br>
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- FOOTER -->
  <footer class="footer">
    <div class="inner">
      <p>&copy; Copyright 영진 4조 RC카팀</p>
    </div>
  </footer>
  
  <!-- JavaScript -->
  <script>
    function scrollToSection(sectionId) {
      document.getElementById(sectionId).scrollIntoView({ behavior: 'smooth' });
    }
  </script>

</body>
</html>
